---
- name: install tools
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-mysqldb

- name: install mysql
  apt: name=mysql-server state=present update_cache=yes


- name: ensure mysql listening on all ports
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = {{ ansible_eth1.ipv4.address }}"
  notify: restart mysql

- name: ensure mysql started
  service: name=mysql state=started enabled=yes


- name: creating database
  mysql_db: name={{ db_name }} state=present

- name: create demo user
  mysql_user: name={{ db_user }} password={{ db_pass }} 
              priv={{ db_name }}.*:ALL host='{{ db_host }}' state=present
